clown_party:
    resource: "@ClownPartyBundle/Resources/config/routing.yml"
    prefix:   /

clown_clown:
    resource: "@ClownClownBundle/Resources/config/routing.yml"
    prefix:   /

MesdPresentationBundle_demo:
    prefix: /ui
    resource: "@MesdPresentationBundle/Resources/config/routing.yml"
