parameters:
#    clown_clown.example.class: Clown\ClownBundle\Example

services:
#    clown_clown.example:
#        class: %clown_clown.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
