<?php

namespace Clown\ClownBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClownSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClownSchoolRepository extends EntityRepository
{
}
