<?php

namespace Clown\ClownBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClownSchoolAttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClownSchoolAttendanceRepository extends EntityRepository
{
}
